# Generated by Django 5.1.4 on 2025-12-28 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessreview',
            old_name='uratting',
            new_name='urating',
        ),
    ]
